version: '3.5'
services:
  db:
    build: db
    ports:
      - 5432:5432
  admin:
    image: dpage/pgadmin4
    ports:
      - 8000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=123456